asyncio.run already handles the event loop variable i was shadowed then in order corrected the issues: only before interrogation the image needs to be decoded.
TypeError: object TaggerInterrogateResponse can't be used in 'await'
expression
TypeError: 'TaggerInterrogateResponse' object is not subscriptable

and now there's something not awaited.. (no completion)